In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv('bank-additional-full.csv', delimiter=';')
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [3]:
df = pd.get_dummies(df, drop_first = True)
df.head()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,y_yes
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,False
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,False
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,False
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,False
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,True,False,False

In [4]:
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)

In [5]:
df

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,y_yes
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,0,0,1,0,0,0,1,0,0
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,0,0,1,0,0,0,1,0,0
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,0,0,1,0,0,0,1,0,0
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,0,0,1,0,0,0,1,0,0
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,334,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,0,1,0,1
41184,46,383,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,0,1,0,0
41185,56,189,2,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,0,1,0,0
41186,44,442,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,0,1,0,1
41187,74,239,3,999,1,-1.1,94.767,-50.8,1.028,4963.6,...,1,0,0,0,0,0,0,0,0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            41188 non-null  int64
 1   duration                       41188 non-null  int64
 2   campaign                       41188 non-null  int64
 3   pdays                          41188 non-null  int64
 4   previous                       41188 non-null  int64
 5   emp.var.rate                   41188 non-null  float64
 6   cons.price.idx                 41188 non-null  float64
 7   cons.conf.idx                  41188 non-null  float64
 8   euribor3m                      41188 non-null  float64
 9   nr.employed                    41188 non-null  float64
 10  job_blue-collar                41188 non-null  int64
 11  job_entrepreneur               41188 non-null  int64
 12  job_housemaid                  41188 non-null  int64
 13  job_management                 41188 non-null  int64
 14  job_retired                    41188 non-null  int64
 15  job_self-employed              41188 non-null  int64
 16  job_services                   41188 non-null  int64
 17  job_student                    41188 non-null  int64
 18  job_technician                 41188 non-null  int64
 19  job_unemployed                 41188 non-null  int64
 20  job_unknown                    41188 non-null  int64
 21  marital_married                41188 non-null  int64
 22  marital_single                 41188 non-null  int64
 23  marital_unknown                41188 non-null  int64
 24  education_basic.6y             41188 non-null  int64
 25  education_basic.9y             41188 non-null  int64
 26  education_high.school          41188 non-null  int64
 27  education_illiterate           41188 non-null  int64
 28  education_professional.course  41188 non-null  int64
 29  education_university.degree    41188 non-null  int64
 30  education_unknown              41188 non-null  int64
 31  default_unknown                41188 non-null  int64
 32  default_yes                    41188 non-null  int64
 33  housing_unknown                41188 non-null  int64
 34  housing_yes                    41188 non-null  int64
 35  loan_unknown                   41188 non-null  int64
 36  loan_yes                       41188 non-null  int64
 37  contact_telephone              41188 non-null  int64
 38  month_aug                      41188 non-null  int64
 39  month_dec                      41188 non-null  int64
 40  month_jul                      41188 non-null  int64
 41  month_jun                      41188 non-null  int64
 42  month_mar                      41188 non-null  int64
 43  month_may                      41188 non-null  int64
 44  month_nov                      41188 non-null  int64
 45  month_oct                      41188 non-null  int64
 46  month_sep                      41188 non-null  int64
 47  day_of_week_mon                41188 non-null  int64
 48  day_of_week_thu                41188 non-null  int64
 49  day_of_week_tue                41188 non-null  int64
 50  day_of_week_wed                41188 non-null  int64
 51  poutcome_nonexistent           41188 non-null  int64
 52  poutcome_success               41188 non-null  int64
 53  y_yes                          41188 non-null  int64
dtypes: float64(5), int64(49)
memory usage: 17.0 MB

54 columns

In [7]:
x = df.drop(columns = ['y_yes'])
y = df['y_yes']


x_train = x.iloc[:40000].to_numpy(dtype=float)
x_test = x.iloc[-1187:].to_numpy(dtype=float)



y_train = y.iloc[:40000].to_numpy(dtype=float)
y_test = y.iloc[-1187:].to_numpy(dtype=float)


if x_train.ndim == 1:
    x_train = x_train.reshape(-1, 1)
if x_test.ndim == 1:
    x_test = x_test.reshape(-1, 1)

x_train.shape

(40000, 53)

## Sigmoid Function

In [8]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

## Propagation Function

In [9]:
def propagation(x,y,w,b):

    
    
    m = x.shape[0]
    z = np.dot(x,w) + b
    y_hat = sigmoid(z)

    print(x.shape)

    epsilon = 1e-15
    cost = (-1/m) * np.sum(y*np.log(y_hat + epsilon) + (1-y)*np.log(1-y_hat + epsilon))

    dw = 1/m * np.dot(x.T, (y_hat-y))
    db = 1/m * np.sum(y_hat-y)

    return cost, dw, db

## Gradient Descent

In [10]:
def gradient(w,b,alpha,dw,db):

    w = w - alpha * dw
    b = b - alpha* db

    print(w.shape)
    
    return w,b

In [11]:
def logistic_reg(x,y):
      
    w = np.zeros(x.shape[1])

    b = 0
    
    alpha = 0.01

    iterations = 1000

    y_hat = np.zeros(y.shape[0])

    for i in range(iterations):

        cost, dw, db = propagation(x, y, w, b)
        w,b = gradient(w,b,dw,db,alpha)

        if i % 100 == 0:
            print(i,":",cost, "\n")

    return w,b

In [12]:
y_pred = np.zeros(y_test.shape[0])

In [13]:
def final_test(x_train,y_train, x_test, y_test):
    w,b = logistic_reg(x_train, y_train)
    z = np.dot(x_test, w) + b
    y_pred = sigmoid(z)
    return y_pred

In [14]:
y_pred = final_test(x_train, y_train, x_test, y_test)
y_pred_class = (y_pred >= 0.5).astype(int)
accuracy = np.mean(y_pred_class == y_test)
print(f"Test Accuracy: {accuracy:.4f}")

(40000, 53)
(53,)
0 : 0.6931471805599435

ValueError: operands could not be broadcast together with shapes (40000,) (53,)

In [ ]:
y_train.shape[0]

In [ ]:

w = np.zeros(x_train.shape[1])
b = 0
z = np.dot(x,w) + b
z